=== openmhealth/schemas/schema/omh/blood-pressure-3.0.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",

    "description": "This schema represents a person's blood pressure as a combination of systolic and diastolic blood pressure.",
    "type": "object",
    "references": [
        {
            "description": "The SNOMED codes represents Blood pressure (observable entity)",
            "url": "http://purl.bioontology.org/ontology/SNOMEDCT/75367002"
        }
    ],
    "definitions": {
        "systolic_blood_pressure": {
            "$ref": "systolic-blood-pressure-1.x.json"
        },
        "diastolic_blood_pressure": {
            "$ref": "diastolic-blood-pressure-1.x.json"
        },
        "time_frame": {
            "$ref": "time-frame-1.x.json"
        },
        "body_posture": {
            "$ref": "body-posture-1.x.json"
        },
        "body_location": {
            "$ref": "body-location-1.x.json"
        },
        "descriptive_statistic": {
            "$ref": "descriptive-statistic-1.x.json"
        }
    },

    "properties": {
        "systolic_blood_pressure": {
            "$ref": "#/definitions/systolic_blood_pressure"
        },
        "diastolic_blood_pressure": {
            "$ref": "#/definitions/diastolic_blood_pressure"
        },
        "effective_time_frame": {
            "$ref": "#/definitions/time_frame"
        },
        "body_posture": {
            "$ref": "#/definitions/body_posture"
        },
        "descriptive_statistic": {
            "$ref": "#/definitions/descriptive_statistic"
        },
        "measurement_location": {
            "description": "The location on the body where the blood pressure measuring device is placed for measurement.",
            "$ref": "#/definitions/body_location"
        }
    },

    "required": [
        "systolic_blood_pressure",
        "diastolic_blood_pressure",
        "effective_time_frame"
    ]
}

=== openmhealth/schemas/test-data/omh/blood-pressure/4.0/shouldPass/with-descriptive-statistic.json
{
    "systolic_blood_pressure": {
        "value": 160,
        "unit": "mmHg"
    },
    "diastolic_blood_pressure": {
        "value": 60,
        "unit": "mmHg"
    },
    "effective_time_frame": {
        "time_interval": {
            "start_date_time": "2020-02-05T07:00:00-08:00",
            "end_date_time": "2020-02-12T07:00:00-08:00"
        }
    },
    "body_posture": "sitting",
    "measurement_location": "left wrist",
    "descriptive_statistic": "maximum"
}

=== openmhealth/schemas/test-data/omh/blood-pressure/4.0/shouldPass/with-posture-and-location.json
{
    "systolic_blood_pressure": {
        "value": 140,
        "unit": "mmHg"
    },
    "diastolic_blood_pressure": {
        "value": 60,
        "unit": "mmHg"
    },
    "body_posture": "sitting",
    "measurement_location": "left upper arm",
    "effective_time_frame": {
        "date_time": "2020-02-05T07:25:00-08:00"
    }
}
