=== openmhealth/schemas/schema/omh/body-temperature-1.0.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",

    "description": "This schema represents a person's body temperature, either a single measurement, or the result of aggregating several measurements made over time (see Descriptive statistic schema for a list of aggregate measures)",
    "type": "object",
    "references": [
        {
            "description": "The SNOMED code represents body temperature (observable entity)",
            "url": "http://purl.bioontology.org/ontology/SNOMEDCT/386725007"
        }
    ],

    "definitions": {
        "temperature_unit_value": {
            "$ref": "temperature-unit-value-1.x.json"
        },
        "time_frame": {
            "$ref": "time-frame-1.x.json"
        },
        "descriptive_statistic": {
            "$ref": "descriptive-statistic-1.x.json"
        },
        "measurement_location": {
            "type": "string",
            "enum": [
                "oral",
                "rectal",
                "vaginal",
                "axillary",
                "otic",
                "wrist",
                "chest",
                "temporal"
            ]
        }
    },

    "properties": {
        "body_temperature": {
            "$ref": "#/definitions/temperature_unit_value"
        },
        "effective_time_frame": {
            "$ref": "#/definitions/time_frame"
        },
        "descriptive_statistic": {
            "$ref": "#/definitions/descriptive_statistic"
        },
        "measurement_location": {
            "$ref": "#/definitions/measurement_location"
        }
    },

    "required": ["body_temperature"]
}

=== openmhealth/schemas/test-data/omh/body-temperature/4.0/shouldPass/valid-temperature-with-statistic.json
{
    "body_temperature": {
        "value": 96.5,
        "unit": "F"
    },
    "effective_time_frame": {
        "time_interval": {
            "start_date_time": "2023-02-05T06:00:00-08:00",
            "end_date_time": "2020-03-06T06:00:00-08:00"
        }
    },
    "measurement_location": "oral",
    "descriptive_statistic": "maximum"
}
